# Generated by Django 3.0.4 on 2020-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTimeStamp', models.DateField(auto_now=True)),
                ('MemberID', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=120, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=120, null=True)),
                ('LastName', models.CharField(blank=True, max_length=120, null=True)),
                ('SpouseFirstName', models.CharField(blank=True, max_length=120, null=True)),
                ('SpouseMemberID', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('SatsangCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('SatsangReference', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('Mandal', models.CharField(blank=True, max_length=50, null=True)),
                ('Relation', models.CharField(blank=True, max_length=50, null=True)),
                ('FatherMemberID', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('MotherMemberID', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('NativePlace', models.CharField(blank=True, max_length=50, null=True)),
                ('NativeCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('ZoneName', models.CharField(blank=True, max_length=50, null=True)),
                ('OtherAppPersonID', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, default='NA', max_length=5, null=True)),
                ('Karyakar', models.CharField(blank=True, default='NA', max_length=5, null=True)),
                ('Volunteer', models.CharField(blank=True, default='NA', max_length=5, null=True)),
                ('GraduationYear', models.CharField(blank=True, max_length=5, null=True)),
                ('Language', models.CharField(blank=True, max_length=200, null=True)),
                ('Profession', models.CharField(blank=True, default='NA', max_length=120, null=True)),
                ('PrimaryEmail', models.CharField(blank=True, default='xyz@xyz.com', max_length=120, null=True)),
                ('PrimaryCellPhone', models.CharField(blank=True, default='(000)-000-0000', max_length=14, null=True)),
                ('PrimaryHomePhone', models.CharField(blank=True, default='(000)-000-0000', max_length=14, null=True)),
                ('Country', models.CharField(blank=True, default='USA', max_length=50, null=True)),
                ('AddressLine1', models.CharField(blank=True, max_length=120, null=True)),
                ('AddressLine2', models.CharField(blank=True, max_length=120, null=True)),
                ('City', models.CharField(blank=True, max_length=120, null=True)),
                ('State', models.CharField(blank=True, max_length=120, null=True)),
                ('Zipcode', models.CharField(blank=True, default='00000', max_length=50, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='IMSProfileImage/')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('EnteredBy', models.CharField(blank=True, default='Unkown', max_length=50, null=True)),
            ],
        ),
    ]
