# Generated by Django 3.0.4 on 2020-04-14 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, max_length=120, null=True, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(blank=True, max_length=120, null=True, verbose_name='State Name')),
            ],
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=120, null=True, verbose_name='Country')),
                ('StateAbbr', models.CharField(blank=True, max_length=120, null=True, verbose_name='State Abbr')),
                ('StateName', models.CharField(blank=True, max_length=120, null=True, verbose_name='State')),
                ('City', models.CharField(blank=True, max_length=120, null=True, verbose_name='City')),
                ('CountyName', models.CharField(blank=True, max_length=120, null=True, verbose_name='County')),
                ('ZipCode', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zip Code')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('loggedIn', models.CharField(blank=True, max_length=30, null=True)),
                ('userAddr', models.CharField(blank=True, max_length=30, null=True)),
                ('userCity', models.CharField(blank=True, max_length=30, null=True)),
                ('userState', models.CharField(blank=True, max_length=2, null=True)),
                ('userLocDict', models.CharField(blank=True, max_length=500, null=True)),
                ('currentTimeStamp', models.DateTimeField(default=datetime.datetime(2020, 4, 14, 14, 46, 41, 45441))),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purpose', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purpose_Code', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purposeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTimeStamp', models.DateField(auto_now=True, null=True)),
                ('Purpose', models.CharField(blank=True, max_length=120, null=True, verbose_name='Purpose')),
                ('Purpose_Code', models.CharField(blank=True, max_length=120, null=True, verbose_name='Purpose Code')),
                ('Purpose_Index', models.CharField(blank=True, max_length=120, null=True, verbose_name='Purpose Index')),
                ('DisplayOnPPT', models.CharField(blank=True, max_length=120, null=True, verbose_name='Purpose Title')),
                ('AnnounceAs', models.CharField(blank=True, max_length=120, null=True, verbose_name='Annoucer Note')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='searchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputSearch', models.CharField(blank=True, max_length=120, null=True, verbose_name='Search')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZipCode', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zip Code')),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(blank=True, max_length=120, null=True, verbose_name='State Name')),
                ('StateAbbr', models.CharField(blank=True, max_length=120, null=True, verbose_name='State Abbr')),
                ('CountryName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Middle Name')),
                ('LastName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name')),
                ('MemberId', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Member Id')),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True, verbose_name='Gender')),
                ('ZipCode', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Zip Code')),
                ('City', models.CharField(blank=True, max_length=120, null=True, verbose_name='City')),
                ('State', models.CharField(blank=True, max_length=120, null=True, verbose_name='State')),
                ('Country', models.CharField(blank=True, max_length=120, null=True, verbose_name='Country')),
                ('Purpose_Code', models.CharField(blank=True, max_length=120, null=True, verbose_name='Purpose Code')),
                ('PurposeIndex', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Purpose Index')),
                ('Memo', models.CharField(blank=True, default='NA', max_length=200, null=True, verbose_name='Memo')),
                ('currentTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('sponsorshipDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sponsor Date')),
                ('DisplayOnPPT', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3, null=True, verbose_name='PPT')),
                ('Announce', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3, null=True, verbose_name='Announce')),
                ('amountReceived', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3, null=True, verbose_name='Amount Received')),
                ('EnteredBy', models.CharField(blank=True, max_length=120, null=True, verbose_name='Entered By')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('Purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.Purpose')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purpose_Index', models.CharField(blank=True, max_length=120, null=True)),
                ('Purpose_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.PurposeCode')),
            ],
        ),
        migrations.AddField(
            model_name='purpose',
            name='Purpose_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.PurposeCode'),
        ),
        migrations.CreateModel(
            name='DisplayPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisplayPurpose', models.CharField(blank=True, max_length=120, null=True)),
                ('Purpose_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.PurposeCode')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountyName', models.CharField(blank=True, max_length=120, null=True, verbose_name='County Name')),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='StateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.State'),
        ),
    ]
