# Generated by Django 3.0.4 on 2020-04-16 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0004_auto_20200416_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 13, 12, 42, 220509)),
        ),
    ]
