# Generated by Django 3.0.4 on 2020-04-18 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0014_auto_20200417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 18, 40, 12, 952729)),
        ),
    ]
