# Generated by Django 3.0.4 on 2020-04-18 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0015_auto_20200418_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 19, 17, 5, 463443)),
        ),
    ]
