# Generated by Django 3.0.4 on 2020-04-20 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0016_auto_20200418_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 11, 19, 18, 556491)),
        ),
    ]
