# Generated by Django 3.0.4 on 2020-04-20 17:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0017_auto_20200420_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='needTofocusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTimeStamp', models.DateField(auto_now=True, null=True)),
                ('NeedToFocus', models.CharField(blank=True, max_length=120, null=True, verbose_name='Need To Focus')),
                ('StartDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('EndDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sponsor Date')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='upcommingEventsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTimeStamp', models.DateField(auto_now=True, null=True)),
                ('upcommingEvents', models.CharField(blank=True, max_length=120, null=True, verbose_name='Upcoming Event')),
                ('StartDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('EndDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sponsor Date')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 37, 33, 416724)),
        ),
    ]
