# Generated by Django 3.0.4 on 2020-04-23 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0020_auto_20200421_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 20, 55, 14, 775858)),
        ),
        migrations.AlterField(
            model_name='purposedata',
            name='Purpose_Index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Purpose Index'),
        ),
    ]
