# Generated by Django 3.0.4 on 2020-05-05 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0023_auto_20200505_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 13, 56, 52, 53635)),
        ),
    ]
