# Generated by Django 3.0.4 on 2020-05-06 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0027_auto_20200506_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 19, 30, 8, 767907)),
        ),
    ]
