# Generated by Django 3.1 on 2021-01-27 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0036_auto_20210127_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 11, 42, 23, 904188)),
        ),
    ]
