# Generated by Django 3.1 on 2021-07-13 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0041_auto_20210713_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 15, 23, 49, 475162)),
        ),
    ]
