# Generated by Django 3.1 on 2021-07-14 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0042_auto_20210713_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 8, 0, 17, 955522)),
        ),
    ]
