# Generated by Django 3.1 on 2021-07-16 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0043_auto_20210714_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 14, 19, 22, 460407)),
        ),
    ]
