# Generated by Django 3.2.5 on 2021-07-16 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0047_alter_loggeduser_currenttimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 14, 35, 16, 680748)),
        ),
    ]
