# Generated by Django 3.2.5 on 2021-07-26 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorApp', '0048_alter_loggeduser_currenttimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='currentTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 11, 44, 32, 60864)),
        ),
        migrations.AlterField(
            model_name='sponsorsdata',
            name='Memo',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True, verbose_name='Announcer Note(s)'),
        ),
    ]
